// This file is auto-generated by @hey-api/openapi-ts

import type {
  Options as ClientOptions,
  TDataShape,
  Client,
} from "@hey-api/client-fetch";
import type {
  OpenAiTranslateModelsData,
  OpenAiTranslateModelsResponses,
  OpenAiTranslateServicesData,
  OpenAiTranslateServicesResponses,
} from "./types.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export class OpenAiTranslate {
  public static openAiTranslateModels<ThrowOnError extends boolean = true>(
    options?: Options<OpenAiTranslateModelsData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      OpenAiTranslateModelsResponses,
      unknown,
      ThrowOnError
    >({
      url: "/umbraco/tm-openai/api/v1/Models",
      ...options,
    });
  }

  public static openAiTranslateServices<ThrowOnError extends boolean = true>(
    options?: Options<OpenAiTranslateServicesData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      OpenAiTranslateServicesResponses,
      unknown,
      ThrowOnError
    >({
      url: "/umbraco/tm-openai/api/v1/Services",
      ...options,
    });
  }
}
