// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise";
import { OpenAPI } from "./core/OpenAPI";
import { request as __request } from "./core/request";
import type {
  OpenAiTranslateModelsResponse,
  OpenAiTranslateServicesResponse,
} from "./types.gen";

/**
 * @returns string OK
 * @throws ApiError
 */
export const openAiTranslateModels =
  (): CancelablePromise<OpenAiTranslateModelsResponse> => {
    return __request(OpenAPI, {
      method: "GET",
      url: "/umbraco/tm-openai/api/v1/Models",
    });
  };

/**
 * @returns string OK
 * @throws ApiError
 */
export const openAiTranslateServices =
  (): CancelablePromise<OpenAiTranslateServicesResponse> => {
    return __request(OpenAPI, {
      method: "GET",
      url: "/umbraco/tm-openai/api/v1/Services",
    });
  };
