// This file is auto-generated by @hey-api/openapi-ts

export type OpenAiTranslateModelsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/umbraco/tm-openai/api/v1/Models";
};

export type OpenAiTranslateModelsResponses = {
  /**
   * OK
   */
  200: Array<string>;
};

export type OpenAiTranslateModelsResponse =
  OpenAiTranslateModelsResponses[keyof OpenAiTranslateModelsResponses];

export type OpenAiTranslateServicesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/umbraco/tm-openai/api/v1/Services";
};

export type OpenAiTranslateServicesResponses = {
  /**
   * OK
   */
  200: Array<string>;
};

export type OpenAiTranslateServicesResponse =
  OpenAiTranslateServicesResponses[keyof OpenAiTranslateServicesResponses];

export type ClientOptions = {
  baseUrl: "http://localhost:11591" | (string & {});
};
